/*
 SettingsGlossary.swift — Справочник и русский глоссарий для всех настроек Krab Ear.

 Создан в рамках F4 / Бриф 1 (спека docs/design-briefs/2026-09-05-horizon-plan.md).
 Содержит понятные человекочитаемые русские названия, категории и описания
 для всех параметров конфигурации бэкенда.

 Позволяет пользователю легко ориентироваться в секции «Все настройки»,
 искать параметры как по-русски, так и по оригинальным английским IPC-ключам.
 В случае появления нового ключа в бэкенде метод lookup автоматически
 возвращает безопасный fallback, гарантируя 100% стабильность.
 */

import Foundation

public struct SettingDescriptor: Sendable, Equatable {
    public let titleRU: String
    public let groupRU: String
    public let descriptionRU: String?

    public init(titleRU: String, groupRU: String, descriptionRU: String? = nil) {
        self.titleRU = titleRU
        self.groupRU = groupRU
        self.descriptionRU = descriptionRU
    }
}

public enum SettingsGlossary {

    /// Поиск описания настройки по IPC-ключу.
    /// Если ключ неизвестен (например, добавлен в новой версии бэкенда),
    /// возвращается безопасный дескриптор с английским ключом и категорией «Разное».
    public static func lookup(_ key: String) -> SettingDescriptor {
        if let desc = items[key] {
            return desc
        }
        return SettingDescriptor(
            titleRU: key,
            groupRU: "Разное",
            descriptionRU: nil
        )
    }

    /// Словарь всех известных параметров конфигурации Krab Ear.
    public static let items: [String: SettingDescriptor] = [
        "action_items_auto_extract": SettingDescriptor(titleRU: "Автоизвлечение поручений", groupRU: "Звонки и встречи", descriptionRU: "Автоматически находить списки задач в тексте транскрипции"),
        "action_items_min_duration_sec": SettingDescriptor(titleRU: "Мин. длительность для задач", groupRU: "Звонки и встречи", descriptionRU: "Минимальная длина аудио в секундах для запуска анализа задач"),
        "active_preset": SettingDescriptor(titleRU: "Активный пресет", groupRU: "Основные и вставка", descriptionRU: "Текущий профиль конфигурации (default, meeting, translation)"),
        "anthropic_api_key": SettingDescriptor(titleRU: "API-ключ Anthropic", groupRU: "Языковые модели и LLM", descriptionRU: "Токен для обращения к API моделей Claude"),
        "audio_ducking_enabled": SettingDescriptor(titleRU: "Приглушение фонового звука", groupRU: "Аудио и запись", descriptionRU: "Автоматически снижать громкость других программ во время записи"),
        "audio_ducking_percent": SettingDescriptor(titleRU: "Процент приглушения звука", groupRU: "Аудио и запись", descriptionRU: "Уровень снижения системной громкости при диктовке (в процентах)"),
        "audio_guarded_read_enabled": SettingDescriptor(titleRU: "Защищенное чтение аудио", groupRU: "Аудио и запись", descriptionRU: "Безопасный опрос аудиобуфера с защитой от блокировки потока"),
        "audio_read_poll_sec": SettingDescriptor(titleRU: "Интервал опроса аудиобуфера", groupRU: "Аудио и запись", descriptionRU: "Период проверки поступления аудиоданных в секундах"),
        "audio_selfheal_empty_threshold": SettingDescriptor(titleRU: "Порог пустых записей для лечения", groupRU: "Аудио и запись", descriptionRU: "Количество подряд идущих пустых записей для реинициализации"),
        "audio_selfheal_enabled": SettingDescriptor(titleRU: "Самовосстановление аудиостека", groupRU: "Аудио и запись", descriptionRU: "Автоматический перезапуск аудиопотока при залипании драйвера"),
        "audio_stream_starve_sec": SettingDescriptor(titleRU: "Таймаут голодания аудиопотока", groupRU: "Аудио и запись", descriptionRU: "Максимальное время отсутствия сэмплов до фиксации сбоя"),
        "auto_dedup_enabled": SettingDescriptor(titleRU: "Автодедупликация записей", groupRU: "История и архив", descriptionRU: "Предотвращать запись дубликатов при случайном двойном вводе"),
        "auto_dedup_threshold": SettingDescriptor(titleRU: "Порог схожести дедупликации", groupRU: "История и архив", descriptionRU: "Коэффициент текстового сходства для признания дублем (0.0–1.0)"),
        "auto_glossary_enabled": SettingDescriptor(titleRU: "Автообучение глоссария", groupRU: "Перевод и языки", descriptionRU: "Автоматически извлекать повторяющиеся пары перевода"),
        "auto_glossary_refresh_hours": SettingDescriptor(titleRU: "Период обновления автоглоссария", groupRU: "Перевод и языки", descriptionRU: "Интервал пересчёта терминологического словаря (часы)"),
        "auto_glossary_top_n": SettingDescriptor(titleRU: "Топ терминов автоглоссария", groupRU: "Перевод и языки", descriptionRU: "Максимальное число генерируемых терминов"),
        "auto_glossary_window_days": SettingDescriptor(titleRU: "Окно автоглоссария (дни)", groupRU: "Перевод и языки", descriptionRU: "Период анализа истории для поиска устойчивых терминов"),
        "auto_learn_corrections_enabled": SettingDescriptor(titleRU: "Обучение на исправлениях", groupRU: "Перевод и языки", descriptionRU: "Запоминать ручные правки пользователя и предлагать автозамены"),
        "auto_paste": SettingDescriptor(titleRU: "Автоматическая вставка", groupRU: "Основные и вставка", descriptionRU: "Автоматически вставлять расшифрованный текст в активное приложение"),
        "auto_purge_check_interval_hours": SettingDescriptor(titleRU: "Периодичность автоочистки", groupRU: "История и архив", descriptionRU: "Интервал проверки устаревших данных хранилища (часы)"),
        "auto_purge_enabled": SettingDescriptor(titleRU: "Автоочистка старых записей", groupRU: "История и архив", descriptionRU: "Автоматически удалять устаревшие транскрипции из истории"),
        "auto_purge_retention_days": SettingDescriptor(titleRU: "Срок хранения истории (дни)", groupRU: "История и архив", descriptionRU: "Количество дней, после которых запись считается устаревшей"),
        "auto_save_transcripts": SettingDescriptor(titleRU: "Автосохранение в Markdown", groupRU: "История и архив", descriptionRU: "Автоматически сохранять каждую диктовку отдельным .md файлом"),
        "auto_start_enabled": SettingDescriptor(titleRU: "Автозапуск при входе", groupRU: "Основные и вставка", descriptionRU: "Запускать Krab Ear автоматически при входе в систему macOS"),
        "background_guard_enabled": SettingDescriptor(titleRU: "Защита от фоновой речи", groupRU: "Фильтры шума и тишины", descriptionRU: "Фильтрация отдалённых голосов (телевизор, радио, коллеги)"),
        "background_guard_max_uniform_active_ratio": SettingDescriptor(titleRU: "Макс. доля монотонных фреймов", groupRU: "Фильтры шума и тишины", descriptionRU: "Допустимая доля стационарного фонового шума в записи"),
        "background_guard_min_peak": SettingDescriptor(titleRU: "Минимальный пик ближней речи", groupRU: "Фильтры шума и тишины", descriptionRU: "Порог амплитуды для отделения ближнего голоса от дальнего фона"),
        "background_guard_min_rms": SettingDescriptor(titleRU: "Минимальный RMS ближней речи", groupRU: "Фильтры шума и тишины", descriptionRU: "Порог энергии для отсечения фонового бормотания"),
        "background_guard_uniform_frame_threshold": SettingDescriptor(titleRU: "Порог равномерности фона", groupRU: "Фильтры шума и тишины", descriptionRU: "Порог обнаружения монотонного акустического фона"),
        "bookmarks_hotkey_enabled": SettingDescriptor(titleRU: "Хоткей закладок", groupRU: "Основные и вставка", descriptionRU: "Разрешить горячую клавишу для добавления записей в избранное"),
        "bulk_reprocess_batch_size": SettingDescriptor(titleRU: "Размер пакета пакетной обработки", groupRU: "История и архив", descriptionRU: "Количество записей в одном батче при массовой обработке"),
        "calendar_link_cache_min": SettingDescriptor(titleRU: "Кэш событий календаря", groupRU: "Звонки и встречи", descriptionRU: "Время жизни кэша событий календаря macOS в минутах"),
        "calendar_link_enabled": SettingDescriptor(titleRU: "Связь с системным календарём", groupRU: "Звонки и встречи", descriptionRU: "Автоматически сопоставлять запись встречи с событиями календаря"),
        "call_auto_summary": SettingDescriptor(titleRU: "Автосаммари телефонного разговора", groupRU: "Звонки и встречи", descriptionRU: "Автоматически генерировать краткие итоги после завершения звонка"),
        "call_budget_usd": SettingDescriptor(titleRU: "Лимит бюджета на один звонок ($)", groupRU: "Звонки и встречи", descriptionRU: "Предельная расчетная стоимость одного телефонного звонка в USD"),
        "call_notify_default": SettingDescriptor(titleRU: "Уведомления о звонках", groupRU: "Звонки и встречи", descriptionRU: "Показывать системные оповещения о входящих и исходящих вызовах"),
        "call_observer_autoplay_audio": SettingDescriptor(titleRU: "Автовоспроизведение аудио звонка", groupRU: "Звонки и встречи", descriptionRU: "Проигрывать звук телефонного разговора в реальном времени"),
        "call_observer_hud_enabled": SettingDescriptor(titleRU: "HUD наблюдателя звонков", groupRU: "Звонки и встречи", descriptionRU: "Плавающий экран Call Observer во время телефонных разговоров"),
        "call_provider": SettingDescriptor(titleRU: "Провайдер телефонии", groupRU: "Звонки и встречи", descriptionRU: "Шлюз для совершения звонков (gateway)"),
        "call_quick_templates": SettingDescriptor(titleRU: "Быстрые реплики для звонков", groupRU: "Звонки и встречи", descriptionRU: "Список заготовленных фраз для отправки в голосовой канал звонка"),
        "capture_source_mode": SettingDescriptor(titleRU: "Источник захвата звука", groupRU: "Аудио и запись", descriptionRU: "Режим ввода: только микрофон (mic) или системный звук"),
        "cleanup_profile": SettingDescriptor(titleRU: "Профиль очистки текста", groupRU: "Основные и вставка", descriptionRU: "Степень нормализации и очистки слов-паразитов (soft, strict)"),
        "clipboard_mode": SettingDescriptor(titleRU: "Режим буфера обмена", groupRU: "Основные и вставка", descriptionRU: "Правило копирования текста в системный буфер (always_copy)"),
        "cloud_rewriter_anthropic_model": SettingDescriptor(titleRU: "Модель Anthropic рерайтера", groupRU: "Языковые модели и LLM", descriptionRU: "Имя модели Claude (например, claude-3-5-haiku)"),
        "cloud_rewriter_api_key": SettingDescriptor(titleRU: "API-ключ облачного рерайтера", groupRU: "Языковые модели и LLM", descriptionRU: "Ключ доступа к выбранному облачному провайдеру"),
        "cloud_rewriter_base_url": SettingDescriptor(titleRU: "Базовый URL облачного API", groupRU: "Языковые модели и LLM", descriptionRU: "Адрес эндпоинта при использовании нестандартного провайдера"),
        "cloud_rewriter_custom_model": SettingDescriptor(titleRU: "Кастомная модель рерайтера", groupRU: "Языковые модели и LLM", descriptionRU: "Имя модели для совместимого стороннего провайдера"),
        "cloud_rewriter_enabled": SettingDescriptor(titleRU: "Облачный фоллбэк рерайтера", groupRU: "Языковые модели и LLM", descriptionRU: "Разрешить облачный LLM при недоступности локального LM Studio"),
        "cloud_rewriter_openai_model": SettingDescriptor(titleRU: "Модель OpenAI рерайтера", groupRU: "Языковые модели и LLM", descriptionRU: "Имя модели OpenAI (например, gpt-4o-mini)"),
        "cloud_rewriter_provider": SettingDescriptor(titleRU: "Провайдер облачного рерайтера", groupRU: "Языковые модели и LLM", descriptionRU: "Сервис облачных моделей: openai, anthropic, custom"),
        "cloud_spend_cap_usd_monthly": SettingDescriptor(titleRU: "Месячный лимит расходов ($)", groupRU: "Языковые модели и LLM", descriptionRU: "Лимит затрат на облачные запросы в месяц (USD)"),
        "cloud_stt_provider": SettingDescriptor(titleRU: "Облачный провайдер STT", groupRU: "Распознавание речи (STT)", descriptionRU: "Внешний сервис транскрибации (groq, deepgram, fal, mistral)"),
        "conversation_brain": SettingDescriptor(titleRU: "Интеллект диалога", groupRU: "Языковые модели и LLM", descriptionRU: "Модель рассуждений голосового собеседника (auto, qwen3)"),
        "conversation_engine": SettingDescriptor(titleRU: "Движок голосового диалога", groupRU: "Языковые модели и LLM", descriptionRU: "Архитектура разговорного ассистента (auto, moshi, seamless)"),
        "datetime_normalization_enabled": SettingDescriptor(titleRU: "Нормализация дат и времени", groupRU: "Основные и вставка", descriptionRU: "Автоматически приводить даты и время к стандартизированному виду"),
        "debug_keep_dictation_wav": SettingDescriptor(titleRU: "Сохранять WAV диктовки для отладки", groupRU: "Аудио и запись", descriptionRU: "Не удалять временные аудиофайлы диктовок (для диагностики)"),
        "diarization_min_duration_sec": SettingDescriptor(titleRU: "Мин. длительность для диаризации", groupRU: "Диаризация и спикеры", descriptionRU: "Порог длины аудиозаписи в секундах, ниже которого спикеры не делятся"),
        "disk_check_interval_min": SettingDescriptor(titleRU: "Интервал проверки диска", groupRU: "Уведомления и мониторинг", descriptionRU: "Периодичность сканирования свободного места в минутах"),
        "disk_critical_gb": SettingDescriptor(titleRU: "Критический порог места на диске (ГБ)", groupRU: "Уведомления и мониторинг", descriptionRU: "Аварийный остаток места, блокирующий тяжелые записи"),
        "disk_monitor_enabled": SettingDescriptor(titleRU: "Мониторинг свободного места на диске", groupRU: "Уведомления и мониторинг", descriptionRU: "Фоновый контроль остатка дискового пространства"),
        "disk_warning_gb": SettingDescriptor(titleRU: "Порог предупреждения о месте (ГБ)", groupRU: "Уведомления и мониторинг", descriptionRU: "Остаток свободного места на диске для выдачи предупреждения"),
        "export_include_speaker_labels": SettingDescriptor(titleRU: "Экспорт меток спикеров", groupRU: "История и архив", descriptionRU: "Включать имена спикеров при экспорте текста транскрипций"),
        "gigaam_idle_unload_sec": SettingDescriptor(titleRU: "Выгрузка GigaAM при простое", groupRU: "Распознавание речи (STT)", descriptionRU: "Таймаут освобождения оперативной памяти GigaAM (секунды)"),
        "history_encryption_enabled": SettingDescriptor(titleRU: "Шифрование базы истории", groupRU: "История и архив", descriptionRU: "Аппаратное шифрование файлов history.ndjson ключом связки ключей"),
        "history_focus_mode": SettingDescriptor(titleRU: "Режим фокуса в истории", groupRU: "Оверлей и интерфейс", descriptionRU: "Скрывать лишние детали интерфейса при просмотре списка записей"),
        "history_large_mb": SettingDescriptor(titleRU: "Порог большого файла истории", groupRU: "История и архив", descriptionRU: "Размер history.ndjson в мегабайтах для предупреждения о росте"),
        "history_page_size": SettingDescriptor(titleRU: "Размер страницы истории", groupRU: "История и архив", descriptionRU: "Количество записей, загружаемых за один раз в журнал"),
        "history_policy": SettingDescriptor(titleRU: "Политика хранения истории", groupRU: "История и архив", descriptionRU: "Срок сохранения записей: без ограничений (unlimited) или по дням"),
        "history_text_density": SettingDescriptor(titleRU: "Плотность текста истории", groupRU: "Оверлей и интерфейс", descriptionRU: "Компактность отображения строк в журнале транскрипций"),
        "hotkey": SettingDescriptor(titleRU: "Глобальная горячая клавиша", groupRU: "Основные и вставка", descriptionRU: "Клавиша активации диктовки (например, right_option_toggle)"),
        "hotkey_mode": SettingDescriptor(titleRU: "Режим хоткея", groupRU: "Основные и вставка", descriptionRU: "Тип срабатывания клавиши: переключение (toggle) или удержание (push-to-talk)"),
        "hotkey_profile": SettingDescriptor(titleRU: "Профиль горячих клавиш", groupRU: "Основные и вставка", descriptionRU: "Схема поведения хоткеев (default, custom)"),
        "inline_translation_target": SettingDescriptor(titleRU: "Язык быстрого перевода", groupRU: "Перевод и языки", descriptionRU: "Целевой язык для быстрого перевода по хоткею"),
        "live_subs_language": SettingDescriptor(titleRU: "Язык живых субтитров", groupRU: "Оверлей и интерфейс", descriptionRU: "Целевой язык для отображения субтитров в реальном времени"),
        "llm_autoload_timeout_sec": SettingDescriptor(titleRU: "Таймаут автозагрузки модели", groupRU: "Языковые модели и LLM", descriptionRU: "Время ожидания готовности модели в LM Studio (секунды)"),
        "llm_brain_lease_enabled": SettingDescriptor(titleRU: "Аренда слота памяти Brain (Lease)", groupRU: "Языковые модели и LLM", descriptionRU: "Координация слота RAM с другими агентами экосистемы"),
        "llm_brain_lease_ttl_sec": SettingDescriptor(titleRU: "Время жизни аренды Brain (TTL)", groupRU: "Языковые модели и LLM", descriptionRU: "Срок удержания модели в памяти перед выгрузкой (секунды)"),
        "llm_brain_model": SettingDescriptor(titleRU: "Основная модель интеллекта (Brain)", groupRU: "Языковые модели и LLM", descriptionRU: "Большая локальная модель для глубокого анализа и саммари"),
        "llm_brain_preload_on_stop": SettingDescriptor(titleRU: "Предзагрузка Brain при остановке", groupRU: "Языковые модели и LLM", descriptionRU: "Загружать модель в память сразу после окончания записи речи"),
        "llm_brain_unload_on_recording": SettingDescriptor(titleRU: "Выгрузка Brain во время записи", groupRU: "Языковые модели и LLM", descriptionRU: "Освобождать память для STT-моделей в момент начала диктовки"),
        "llm_idle_keepalive_enabled": SettingDescriptor(titleRU: "Поддержание активности LLM", groupRU: "Языковые модели и LLM", descriptionRU: "Периодический пинг локальной модели для предотвращения выгрузки"),
        "llm_model": SettingDescriptor(titleRU: "Локальная модель LLM", groupRU: "Языковые модели и LLM", descriptionRU: "Идентификатор модели в LM Studio для локальной обработки"),
        "llm_probe_enabled": SettingDescriptor(titleRU: "Проверка доступности LLM", groupRU: "Языковые модели и LLM", descriptionRU: "Фоновый мониторинг статуса сервера LM Studio"),
        "llm_probe_interval_sec": SettingDescriptor(titleRU: "Интервал проверки LLM", groupRU: "Языковые модели и LLM", descriptionRU: "Периодичность проверки доступности локального LLM-сервера (сек)"),
        "llm_rewrite_enabled": SettingDescriptor(titleRU: "LLM-рерайтер диктовки", groupRU: "Языковые модели и LLM", descriptionRU: "Автоматическое исправление стиля и пунктуации через нейросеть"),
        "lm_studio_api_key": SettingDescriptor(titleRU: "Ключ авторизации LM Studio", groupRU: "Языковые модели и LLM", descriptionRU: "Bearer токен для доступа к API LM Studio v0.3+"),
        "meeting_chunk_stt_interval_sec": SettingDescriptor(titleRU: "Интервал чанков записи встречи", groupRU: "Звонки и встречи", descriptionRU: "Длина порции аудио для распознавания длинных встреч (секунды)"),
        "meeting_diar_interval_sec": SettingDescriptor(titleRU: "Интервал диаризации встречи", groupRU: "Диаризация и спикеры", descriptionRU: "Частота обновления раскладки по спикерам во время встречи (сек)"),
        "meeting_diar_window_sec": SettingDescriptor(titleRU: "Окно анализа диаризации", groupRU: "Диаризация и спикеры", descriptionRU: "Длина скользящего окна аудио для кластеризации голосов (сек)"),
        "meeting_items_interval_sec": SettingDescriptor(titleRU: "Интервал извлечения задач встречи", groupRU: "Звонки и встречи", descriptionRU: "Частота фонового поиска договоренностей и задач (секунды)"),
        "meeting_items_language": SettingDescriptor(titleRU: "Язык задач и итогов встречи", groupRU: "Звонки и встречи", descriptionRU: "Язык, на котором формулируются action items встречи"),
        "meeting_live_speakers_enabled": SettingDescriptor(titleRU: "Живое разделение спикеров встречи", groupRU: "Диаризация и спикеры", descriptionRU: "Отображать смену говорящих в реальном времени"),
        "meeting_speaker_match_threshold": SettingDescriptor(titleRU: "Порог совпадения спикеров встречи", groupRU: "Диаризация и спикеры", descriptionRU: "Степень схожести голоса для объединения сегментов"),
        "memory_conductor_enabled": SettingDescriptor(titleRU: "Кондуктор оперативной памяти", groupRU: "Уведомления и мониторинг", descriptionRU: "Координация загрузки тяжелых моделей в RAM macOS"),
        "memory_conductor_enforce": SettingDescriptor(titleRU: "Принудительное освобождение RAM", groupRU: "Уведомления и мониторинг", descriptionRU: "Разрешить кондуктору принудительно выгружать неиспользуемые модели"),
        "memory_conductor_enforce_brain": SettingDescriptor(titleRU: "Принудительная выгрузка Brain", groupRU: "Уведомления и мониторинг", descriptionRU: "Кондуктор может выгружать модель Brain (строго запрещено политикой)"),
        "memory_conductor_enforce_gigaam": SettingDescriptor(titleRU: "Принудительная выгрузка GigaAM", groupRU: "Уведомления и мониторинг", descriptionRU: "Кондуктор может выгружать модель GigaAM"),
        "memory_conductor_enforce_recording_sequence": SettingDescriptor(titleRU: "Соблюдение очереди при записи", groupRU: "Уведомления и мониторинг", descriptionRU: "Очередность предоставления памяти во время активной диктовки"),
        "memory_conductor_enforce_rewriter": SettingDescriptor(titleRU: "Принудительная выгрузка рерайтера", groupRU: "Уведомления и мониторинг", descriptionRU: "Кондуктор может выгружать рерайтер"),
        "memory_conductor_enforce_whisper": SettingDescriptor(titleRU: "Принудительная выгрузка Whisper", groupRU: "Уведомления и мониторинг", descriptionRU: "Кондуктор может выгружать модель Whisper"),
        "memory_evict_cooldown_sec": SettingDescriptor(titleRU: "Таймаут остывания очистки памяти", groupRU: "Уведомления и мониторинг", descriptionRU: "Задержка между повторными циклами принудительной выгрузки (сек)"),
        "memory_pressure_streak_ticks": SettingDescriptor(titleRU: "Серия тактов давления памяти", groupRU: "Уведомления и мониторинг", descriptionRU: "Число подтверждений memory pressure подряд до вызова защиты"),
        "mlx_crash_recovery_enabled": SettingDescriptor(titleRU: "Восстановление после сбоя MLX", groupRU: "Уведомления и мониторинг", descriptionRU: "Мягкий перезапуск подпроцесса транскрибации при фатальной ошибке Metal"),
        "mlx_oom_auto_unload_cooldown_sec": SettingDescriptor(titleRU: "Кулдаун выгрузки при OOM", groupRU: "Уведомления и мониторинг", descriptionRU: "Задержка перед повторным запуском моделей после OOM (секунды)"),
        "mlx_oom_auto_unload_enabled": SettingDescriptor(titleRU: "Автовыгрузка MLX при OOM", groupRU: "Уведомления и мониторинг", descriptionRU: "Автоматическое освобождение моделей при нехватке видеопамяти Metal"),
        "mlx_transcribe_timeout_sec": SettingDescriptor(titleRU: "Таймаут инференса MLX", groupRU: "Распознавание речи (STT)", descriptionRU: "Предельное время выполнения транскрибации на Apple Silicon MLX"),
        "mode": SettingDescriptor(titleRU: "Режим запуска", groupRU: "Основные и вставка", descriptionRU: "Режим работы бэкенда (headless, gui или standalone)"),
        "network_mode": SettingDescriptor(titleRU: "Сетевой режим", groupRU: "Основные и вставка", descriptionRU: "Политика использования сети (offline_default, cloud_allowed)"),
        "notifications_enabled": SettingDescriptor(titleRU: "Системные уведомления", groupRU: "Уведомления и мониторинг", descriptionRU: "Разрешить отправку уведомлений в Центр уведомлений macOS"),
        "notify_confidence_threshold": SettingDescriptor(titleRU: "Порог предупреждения об уверенности", groupRU: "Уведомления и мониторинг", descriptionRU: "Значение уверенности (0.0–1.0), ниже которого слать сигнал"),
        "notify_on_import_complete": SettingDescriptor(titleRU: "Оповещать об окончании импорта", groupRU: "Уведомления и мониторинг", descriptionRU: "Сигнализировать о готовности расшифровки аудиофайла"),
        "notify_on_llm_failure": SettingDescriptor(titleRU: "Оповещать об ошибках LLM", groupRU: "Уведомления и мониторинг", descriptionRU: "Уведомлять при сбоях локального или облачного нейросетевого рерайтера"),
        "notify_on_low_confidence": SettingDescriptor(titleRU: "Оповещать при низкой уверенности", groupRU: "Уведомления и мониторинг", descriptionRU: "Предупреждать, если качество распознавания фразы ниже нормы"),
        "notify_sound_enabled": SettingDescriptor(titleRU: "Звук при уведомлениях", groupRU: "Уведомления и мониторинг", descriptionRU: "Сопровождать всплывающие уведомления системным звуком"),
        "number_normalization_enabled": SettingDescriptor(titleRU: "Нормализация чисел", groupRU: "Основные и вставка", descriptionRU: "Преобразовывать числительные словами в цифры (триста -> 300)"),
        "onboarding_completed": SettingDescriptor(titleRU: "Онбординг завершён", groupRU: "Основные и вставка", descriptionRU: "Флаг прохождения первичной настройки приложения"),
        "overlay_follow_cursor": SettingDescriptor(titleRU: "Следование оверлея за курсором", groupRU: "Оверлей и интерфейс", descriptionRU: "Перемещать индикатор диктовки вслед за курсором мыши"),
        "overlay_opacity_percent": SettingDescriptor(titleRU: "Непрозрачность оверлея", groupRU: "Оверлей и интерфейс", descriptionRU: "Прозрачность плавающего индикатора диктовки (в процентах)"),
        "paste_app_memory_enabled": SettingDescriptor(titleRU: "Память контекста приложений", groupRU: "Основные и вставка", descriptionRU: "Запоминать специфику вставки текста для разных программ"),
        "phonetic_vocab_enabled": SettingDescriptor(titleRU: "Фонетический словарь замен", groupRU: "Распознавание речи (STT)", descriptionRU: "Автоматическая коррекция фонетически созвучных ошибок STT"),
        "pipeline_v2_enabled": SettingDescriptor(titleRU: "Пайплайн распознавания v2", groupRU: "Распознавание речи (STT)", descriptionRU: "Современный многоязычный конвейер STT с улучшенным роутингом"),
        "play_start_sound": SettingDescriptor(titleRU: "Звук начала записи", groupRU: "Основные и вставка", descriptionRU: "Воспроизводить звуковой сигнал при старте диктовки"),
        "preset_quick_switch_hotkey": SettingDescriptor(titleRU: "Хоткей переключения пресетов", groupRU: "Основные и вставка", descriptionRU: "Комбинация клавиш для быстрой смены профиля настроек"),
        "privacy_mode_enabled": SettingDescriptor(titleRU: "Режим приватности", groupRU: "Безопасность и приватность", descriptionRU: "Маскирование всех текстов в интерфейсе и запрет сетевых запросов"),
        "quality_profile": SettingDescriptor(titleRU: "Профиль качества", groupRU: "Основные и вставка", descriptionRU: "Баланс скорости и точности распознавания (fast, balanced, max)"),
        "quick_capture_hotkey": SettingDescriptor(titleRU: "Хоткей Quick Capture", groupRU: "Основные и вставка", descriptionRU: "Комбинация клавиш для быстрого захвата мыслей и заметок"),
        "quick_capture_obsidian_sync": SettingDescriptor(titleRU: "Синхронизация с Obsidian", groupRU: "Основные и вставка", descriptionRU: "Автоматически экспортировать быстрые заметки в хранилище Obsidian"),
        "quick_capture_send_to_notes": SettingDescriptor(titleRU: "Экспорт в Apple Notes", groupRU: "Основные и вставка", descriptionRU: "Отправлять быстрые заметки в стандартные Заметки macOS"),
        "quick_capture_show_panel": SettingDescriptor(titleRU: "Панель Quick Capture", groupRU: "Основные и вставка", descriptionRU: "Отображать всплывающую панель при вызове быстрого захвата"),
        "quick_edit_enabled": SettingDescriptor(titleRU: "Быстрое редактирование", groupRU: "Основные и вставка", descriptionRU: "Включить всплывающее окно QuickEdit после диктовки"),
        "quick_edit_timeout_sec": SettingDescriptor(titleRU: "Таймаут QuickEdit", groupRU: "Основные и вставка", descriptionRU: "Время ожидания подтверждения правки в секундах"),
        "realtime_partial_enabled": SettingDescriptor(titleRU: "Частичные результаты в оверлее", groupRU: "Оверлей и интерфейс", descriptionRU: "Отображать промежуточные гипотезы распознавания"),
        "realtime_preview_enabled": SettingDescriptor(titleRU: "Предпросмотр в реальном времени", groupRU: "Оверлей и интерфейс", descriptionRU: "Показывать распознаваемый текст в процессе диктовки"),
        "realtime_silence_filter_enabled": SettingDescriptor(titleRU: "Реалтайм фильтр тишины", groupRU: "Фильтры шума и тишины", descriptionRU: "Отсечение тишины в потоковом режиме реального времени"),
        "recap_backend": SettingDescriptor(titleRU: "Бэкенд генерации сводки", groupRU: "Звонки и встречи", descriptionRU: "Движок для агрегации и составления дневного саммари"),
        "recap_email_enabled": SettingDescriptor(titleRU: "Отправка сводки на Email", groupRU: "Звонки и встречи", descriptionRU: "Автоматически отсылать дайджест дня по электронной почте"),
        "recap_email_to": SettingDescriptor(titleRU: "Email получателя сводки", groupRU: "Звонки и встречи", descriptionRU: "Адрес электронной почты для ежедневных отчетов"),
        "recap_time_hour": SettingDescriptor(titleRU: "Час отправки ежедневной сводки", groupRU: "Звонки и встречи", descriptionRU: "Время суток для генерации и отправки отчета (0–23)"),
        "recording_owner_enforce": SettingDescriptor(titleRU: "Контроль владельца записи", groupRU: "Аудио и запись", descriptionRU: "Строгая проверка прав процесса на управление записью"),
        "recording_spill_enabled": SettingDescriptor(titleRU: "Сброс аудио на диск при нехватке памяти", groupRU: "Аудио и запись", descriptionRU: "Буферизация длинных записей во временные файлы"),
        "rest_api_auth_enabled": SettingDescriptor(titleRU: "Авторизация REST API", groupRU: "Безопасность и приватность", descriptionRU: "Требовать токен авторизации для любых запросов к локальному REST API"),
        "rest_in_process_enabled": SettingDescriptor(titleRU: "REST внутри основного процесса", groupRU: "Безопасность и приватность", descriptionRU: "Запуск REST-сервера внутри процесса бэкенда (выключено)"),
        "rewriter_fallback_chain": SettingDescriptor(titleRU: "Цепочка отказоустойчивости рерайтера", groupRU: "Языковые модели и LLM", descriptionRU: "Последовательность переключения между локальной и облачной моделями"),
        "rewriter_idle_unload_sec": SettingDescriptor(titleRU: "Выгрузка рерайтера при простое", groupRU: "Языковые модели и LLM", descriptionRU: "Таймаут выгрузки модели рерайтера из оперативной памяти"),
        "rewriter_warmup_on_startup": SettingDescriptor(titleRU: "Прогрев рерайтера при старте", groupRU: "Языковые модели и LLM", descriptionRU: "Тестовый холостой запрос к рерайтеру при запуске бэкенда"),
        "rewriter_warmup_timeout_sec": SettingDescriptor(titleRU: "Таймаут прогрева рерайтера", groupRU: "Языковые модели и LLM", descriptionRU: "Время ожидания завершения тестового запроса прогрева (сек)"),
        "rt_partial_buffer_sec": SettingDescriptor(titleRU: "Буфер частичных результатов", groupRU: "Оверлей и интерфейс", descriptionRU: "Размер скользящего аудио-окна для промежуточного STT"),
        "rt_partial_interval_sec": SettingDescriptor(titleRU: "Интервал частичных результатов", groupRU: "Оверлей и интерфейс", descriptionRU: "Периодичность обновления промежуточного текста (секунды)"),
        "rt_silence_check_sec": SettingDescriptor(titleRU: "Интервал проверки тишины в потоке", groupRU: "Фильтры шума и тишины", descriptionRU: "Частота анализа пауз при потоковом вводе (секунды)"),
        "rt_silence_max_sec": SettingDescriptor(titleRU: "Максимальная пауза в потоке", groupRU: "Фильтры шума и тишины", descriptionRU: "Порог тишины, после которого аудиосэмплы отбрасываются"),
        "rt_silence_window_sec": SettingDescriptor(titleRU: "Окно анализа потоковой тишины", groupRU: "Фильтры шума и тишины", descriptionRU: "Длина анализируемого фрагмента для детекции тишины (секунды)"),
        "selected_input_device": SettingDescriptor(titleRU: "Входное аудиоустройство", groupRU: "Основные и вставка", descriptionRU: "Микрофон для записи (пусто — системный микрофон по умолчанию)"),
        "semantic_search_auto_index": SettingDescriptor(titleRU: "Автоиндексация семантики", groupRU: "История и архив", descriptionRU: "Автоматически векторизовать новые записи при их создании"),
        "semantic_search_enabled": SettingDescriptor(titleRU: "Семантический поиск по смыслу", groupRU: "История и архив", descriptionRU: "Поиск в истории по значению и контексту через эмбеддинги"),
        "semantic_search_idle_unload_sec": SettingDescriptor(titleRU: "Выгрузка семантической модели", groupRU: "История и архив", descriptionRU: "Таймаут выгрузки модели поиска из памяти при простое (сек)"),
        "semantic_search_model": SettingDescriptor(titleRU: "Модель эмбеддингов семантики", groupRU: "История и архив", descriptionRU: "Нейросеть для векторизации записей истории"),
        "settings_read_lock_timeout_sec": SettingDescriptor(titleRU: "Таймаут блокировки настроек", groupRU: "Безопасность и приватность", descriptionRU: "Максимальное время ожидания чтения файла settings.json (секунды)"),
        "show_dock_icon": SettingDescriptor(titleRU: "Иконка в Dock", groupRU: "Основные и вставка", descriptionRU: "Показывать иконку приложения в панели Dock macOS"),
        "silence_guard_active_ratio_threshold": SettingDescriptor(titleRU: "Порог доли активных фреймов", groupRU: "Фильтры шума и тишины", descriptionRU: "Минимальный процент речевых фреймов во фрагменте"),
        "silence_guard_enabled": SettingDescriptor(titleRU: "Защита от записи тишины", groupRU: "Фильтры шума и тишины", descriptionRU: "Предотвращение ложного распознавания пустого аудио"),
        "silence_guard_peak_threshold": SettingDescriptor(titleRU: "Порог пиковой амплитуды тишины", groupRU: "Фильтры шума и тишины", descriptionRU: "Минимальный пиковый уровень сигнала для детекции речи"),
        "silence_guard_rms_threshold": SettingDescriptor(titleRU: "Порог среднеквадратичной энергии тишины", groupRU: "Фильтры шума и тишины", descriptionRU: "Минимальная средняя амплитуда полезного сигнала (RMS)"),
        "sip_from_number": SettingDescriptor(titleRU: "Исходящий SIP-номер", groupRU: "Звонки и встречи", descriptionRU: "Телефонный номер абонента для исходящих звонков"),
        "sip_password": SettingDescriptor(titleRU: "Пароль SIP", groupRU: "Звонки и встречи", descriptionRU: "Пароль для авторизации на SIP-сервере"),
        "sip_port": SettingDescriptor(titleRU: "Порт SIP-сервера", groupRU: "Звонки и встречи", descriptionRU: "Сетевой порт SIP-сервера (дефолт 5060)"),
        "sip_proxy": SettingDescriptor(titleRU: "Прокси-сервер SIP", groupRU: "Звонки и встречи", descriptionRU: "Адрес промежуточного SIP Outbound Proxy"),
        "sip_server": SettingDescriptor(titleRU: "SIP-сервер", groupRU: "Звонки и встречи", descriptionRU: "Адрес АТС для подключения прямой SIP-телефонии"),
        "sip_user": SettingDescriptor(titleRU: "Пользователь SIP", groupRU: "Звонки и встречи", descriptionRU: "Логин учетной записи SIP-телефонии"),
        "smart_field_format_enabled": SettingDescriptor(titleRU: "Умное форматирование полей", groupRU: "Основные и вставка", descriptionRU: "Адаптировать текст под контекст активного поля ввода"),
        "smart_silence_skip_enabled": SettingDescriptor(titleRU: "Умный пропуск пауз", groupRU: "Фильтры шума и тишины", descriptionRU: "Исключение пауз длиннее 1 секунды из аудио перед передачей в STT"),
        "smtp_host": SettingDescriptor(titleRU: "SMTP-сервер", groupRU: "Уведомления и мониторинг", descriptionRU: "Почтовый сервер для отправки уведомлений и сводок"),
        "smtp_port": SettingDescriptor(titleRU: "Порт SMTP-сервера", groupRU: "Уведомления и мониторинг", descriptionRU: "Сетевой порт почтового сервера (например, 587 или 465)"),
        "smtp_use_ssl": SettingDescriptor(titleRU: "Использовать SSL для SMTP", groupRU: "Уведомления и мониторинг", descriptionRU: "Прямое SSL-подключение к почтовому серверу"),
        "smtp_use_tls": SettingDescriptor(titleRU: "Использовать TLS для SMTP", groupRU: "Уведомления и мониторинг", descriptionRU: "Включить шифрование STARTTLS при подключении к почте"),
        "smtp_user": SettingDescriptor(titleRU: "Пользователь SMTP", groupRU: "Уведомления и мониторинг", descriptionRU: "Логин почтового аккаунта для рассылки"),
        "stop_tail_trim_ms": SettingDescriptor(titleRU: "Обрезка хвоста записи", groupRU: "Аудио и запись", descriptionRU: "Длительность отсечения шума и щелчка клавиши после остановки (мс)"),
        "streaming_paste_enabled": SettingDescriptor(titleRU: "Потоковая вставка", groupRU: "Основные и вставка", descriptionRU: "Вставлять слова по мере их распознавания в реальном времени"),
        "stt_audio_lang_id_enabled": SettingDescriptor(titleRU: "Акустическая детекция языка (LID)", groupRU: "Распознавание речи (STT)", descriptionRU: "Определение языка речи напрямую по акустическому спектру"),
        "stt_audio_lang_id_preview_sec": SettingDescriptor(titleRU: "Длина превью для LID", groupRU: "Распознавание речи (STT)", descriptionRU: "Длительность начального фрагмента речи для детекции языка (сек)"),
        "stt_code_switching_detect": SettingDescriptor(titleRU: "Детекция смешения языков", groupRU: "Распознавание речи (STT)", descriptionRU: "Обнаружение переключения между языками внутри одной фразы"),
        "stt_code_switching_threshold": SettingDescriptor(titleRU: "Порог переключения языков", groupRU: "Распознавание речи (STT)", descriptionRU: "Чувствительность детектора билингвальной речи"),
        "stt_denoise_enabled": SettingDescriptor(titleRU: "Шумоподавление STT", groupRU: "Фильтры шума и тишины", descriptionRU: "Адаптивная фильтрация фонового акустического шума"),
        "stt_denoise_snr_threshold_db": SettingDescriptor(titleRU: "Порог сигнал/шум (SNR)", groupRU: "Фильтры шума и тишины", descriptionRU: "Пороговое соотношение сигнал/шум в децибелах для шумоподавления"),
        "stt_denoise_strength": SettingDescriptor(titleRU: "Степень шумоподавления", groupRU: "Фильтры шума и тишины", descriptionRU: "Уровень фильтрации шума: мягкий, умеренный (moderate), агрессивный"),
        "stt_dialogue_hint_threshold": SettingDescriptor(titleRU: "Порог диалоговых подсказок", groupRU: "Распознавание речи (STT)", descriptionRU: "Порог уверенности для добавления диалогового контекста"),
        "stt_download_stall_timeout_sec": SettingDescriptor(titleRU: "Таймаут зависания скачивания", groupRU: "Распознавание речи (STT)", descriptionRU: "Время ожидания ответа при загрузке весов моделей из сети"),
        "stt_en_primary_model": SettingDescriptor(titleRU: "Основная модель для английского (EN)", groupRU: "Распознавание речи (STT)", descriptionRU: "Движок для распознавания английской речи"),
        "stt_es_primary_model": SettingDescriptor(titleRU: "Основная модель для испанского (ES)", groupRU: "Распознавание речи (STT)", descriptionRU: "Движок для распознавания испанской речи"),
        "stt_gigaam_device": SettingDescriptor(titleRU: "Устройство GigaAM", groupRU: "Распознавание речи (STT)", descriptionRU: "Аппаратный ускоритель для GigaAM (mps, cpu)"),
        "stt_gigaam_enabled": SettingDescriptor(titleRU: "Использовать GigaAM v3", groupRU: "Распознавание речи (STT)", descriptionRU: "Активировать модель GigaAM v3 для русскоязычной диктовки"),
        "stt_gigaam_mode": SettingDescriptor(titleRU: "Режим интеграции GigaAM", groupRU: "Распознавание речи (STT)", descriptionRU: "Архитектура исполнения GigaAM (inprocess или subprocess worker)"),
        "stt_gigaam_transport": SettingDescriptor(titleRU: "Транспорт воркера GigaAM", groupRU: "Распознавание речи (STT)", descriptionRU: "Протокол связи с воркером GigaAM (pipe_json)"),
        "stt_hotwords": SettingDescriptor(titleRU: "Горячие слова (подсказки)", groupRU: "Распознавание речи (STT)", descriptionRU: "Список ключевых слов и терминов для подсказки STT"),
        "stt_hotwords_en": SettingDescriptor(titleRU: "Горячие слова (английский)", groupRU: "Распознавание речи (STT)", descriptionRU: "Специфичный словарь английских подсказок"),
        "stt_hotwords_enabled": SettingDescriptor(titleRU: "Использовать горячие слова", groupRU: "Распознавание речи (STT)", descriptionRU: "Передавать контекстные подсказки в модель STT"),
        "stt_hotwords_es": SettingDescriptor(titleRU: "Горячие слова (испанский)", groupRU: "Распознавание речи (STT)", descriptionRU: "Специфичный словарь испанских подсказок"),
        "stt_hotwords_ru": SettingDescriptor(titleRU: "Горячие слова (русский)", groupRU: "Распознавание речи (STT)", descriptionRU: "Специфичный словарь русских подсказок и терминологии"),
        "stt_language_routing_enabled": SettingDescriptor(titleRU: "Языковая маршрутизация STT", groupRU: "Распознавание речи (STT)", descriptionRU: "Автоматический выбор движка в зависимости от языка речи"),
        "stt_loop_retry_enabled": SettingDescriptor(titleRU: "Повтор при зацикливании STT", groupRU: "Распознавание речи (STT)", descriptionRU: "Автоматический перезапуск распознавания при обнаружении повторов галлюцинаций"),
        "stt_max_retries": SettingDescriptor(titleRU: "Максимум повторных попыток STT", groupRU: "Распознавание речи (STT)", descriptionRU: "Предельное число попыток перезапуска распознавания"),
        "stt_min_confidence_threshold": SettingDescriptor(titleRU: "Минимальный порог уверенности STT", groupRU: "Распознавание речи (STT)", descriptionRU: "Порог (0.0–1.0), ниже которого запускается повторный проход"),
        "stt_multipass_enabled": SettingDescriptor(titleRU: "Многопроходный ретрай STT", groupRU: "Распознавание речи (STT)", descriptionRU: "Повторная транскрибация альтернативной моделью при низкой уверенности"),
        "stt_other_primary_model": SettingDescriptor(titleRU: "Основная модель для остальных языков", groupRU: "Распознавание речи (STT)", descriptionRU: "Движок для распознавания прочих языков"),
        "stt_punctuation_llm_pass_enabled": SettingDescriptor(titleRU: "Пунктуация через LLM", groupRU: "Языковые модели и LLM", descriptionRU: "Лёгкий проход нейросетью строго для расстановки знаков препинания"),
        "stt_routing": SettingDescriptor(titleRU: "Схема маршрутизации STT", groupRU: "Распознавание речи (STT)", descriptionRU: "Правило выбора модели по языкам и длительности фрагмента"),
        "stt_ru_finetune_model": SettingDescriptor(titleRU: "Путь к файнтьюну RU", groupRU: "Распознавание речи (STT)", descriptionRU: "Идентификатор или путь к файлам дообученной модели"),
        "stt_ru_primary_model": SettingDescriptor(titleRU: "Основная модель для русского (RU)", groupRU: "Распознавание речи (STT)", descriptionRU: "Движок для распознавания русской речи (gigaam или whisper)"),
        "stt_sensevoice_device": SettingDescriptor(titleRU: "Устройство SenseVoice", groupRU: "Распознавание речи (STT)", descriptionRU: "Ускоритель для работы SenseVoice (mps, cpu)"),
        "stt_sensevoice_enabled": SettingDescriptor(titleRU: "Использовать SenseVoice", groupRU: "Распознавание речи (STT)", descriptionRU: "Активировать сверхбыстрый мультиязычный движок SenseVoice"),
        "stt_sensevoice_model": SettingDescriptor(titleRU: "Модель SenseVoice", groupRU: "Распознавание речи (STT)", descriptionRU: "Имя весов модели SenseVoice"),
        "stt_speaker_aware_prompt_enabled": SettingDescriptor(titleRU: "Промпт с учётом спикера", groupRU: "Распознавание речи (STT)", descriptionRU: "Учитывать идентификатор говорящего при генерации подсказок"),
        "stt_streaming_chunk_sec": SettingDescriptor(titleRU: "Размер потокового чанка", groupRU: "Распознавание речи (STT)", descriptionRU: "Длительность порции аудио для потокового распознавания (сек)"),
        "stt_streaming_enabled": SettingDescriptor(titleRU: "Потоковое распознавание", groupRU: "Распознавание речи (STT)", descriptionRU: "Активировать чанковое потоковое декодирование речи"),
        "stt_streaming_min_audio_sec": SettingDescriptor(titleRU: "Минимум аудио для потока", groupRU: "Распознавание речи (STT)", descriptionRU: "Минимальная длина накопившегося фрагмента для старта чанка"),
        "stt_streaming_overlap_sec": SettingDescriptor(titleRU: "Перекрытие потоковых чанков", groupRU: "Распознавание речи (STT)", descriptionRU: "Размер нахлёста между соседними чанками для сшивки слов (сек)"),
        "stt_timeout_batch_factor": SettingDescriptor(titleRU: "Множитель пакетного таймаута", groupRU: "Распознавание речи (STT)", descriptionRU: "Коэффициент таймаута для обработки файлов и встреч"),
        "stt_timeout_batch_max_sec": SettingDescriptor(titleRU: "Макс. пакетный таймаут", groupRU: "Распознавание речи (STT)", descriptionRU: "Предельный таймаут распознавания для пакетных задач"),
        "stt_timeout_interactive_factor": SettingDescriptor(titleRU: "Множитель интерактивного таймаута", groupRU: "Распознавание речи (STT)", descriptionRU: "Коэффициент расчёта дедлайна относительно длины аудио"),
        "stt_timeout_interactive_max_sec": SettingDescriptor(titleRU: "Макс. интерактивный таймаут", groupRU: "Распознавание речи (STT)", descriptionRU: "Потолок времени ожидания диктовки в секундах"),
        "stt_timeout_overhead_sec": SettingDescriptor(titleRU: "Фиксированный накладной таймаут", groupRU: "Распознавание речи (STT)", descriptionRU: "Базовый запас времени на запуск и инициализацию (секунды)"),
        "stt_timeout_request_attempts": SettingDescriptor(titleRU: "Попытки запроса к STT", groupRU: "Распознавание речи (STT)", descriptionRU: "Число попыток отправки аудио при сетевых ошибках"),
        "stt_use_ru_finetune": SettingDescriptor(titleRU: "Использовать кастомный файнтьюн RU", groupRU: "Распознавание речи (STT)", descriptionRU: "Подключать дообученную русскую модель при наличии"),
        "stt_vad_prefilter_enabled": SettingDescriptor(titleRU: "VAD фильтр тишины перед STT", groupRU: "Фильтры шума и тишины", descriptionRU: "Детекция голосовой активности для отсечения тишины до модели"),
        "stt_vad_silence_trim_threshold_sec": SettingDescriptor(titleRU: "Порог обрезки тишины VAD", groupRU: "Фильтры шума и тишины", descriptionRU: "Минимальная длительность пауз в секундах для их вырезания"),
        "stt_warmup_on_startup": SettingDescriptor(titleRU: "Прогрев STT при старте", groupRU: "Распознавание речи (STT)", descriptionRU: "Предварительная загрузка и тестовый прогон моделей при запуске"),
        "text_snippets_enabled": SettingDescriptor(titleRU: "Текстовые сниппеты", groupRU: "Основные и вставка", descriptionRU: "Разрешить подстановку заранее заготовленных текстовых шаблонов"),
        "text_templates": SettingDescriptor(titleRU: "Шаблоны текста", groupRU: "Основные и вставка", descriptionRU: "Словарь пользовательских шаблонов и шаблонов ответов"),
        "translate_and_paste": SettingDescriptor(titleRU: "Переводить и вставлять", groupRU: "Перевод и языки", descriptionRU: "Автоматически вставлять переведённый текст вместо исходного"),
        "translation_glossary": SettingDescriptor(titleRU: "Глоссарий терминов перевода", groupRU: "Перевод и языки", descriptionRU: "Словарь фиксированных переводов специальных терминов"),
        "translation_mode": SettingDescriptor(titleRU: "Режим перевода", groupRU: "Перевод и языки", descriptionRU: "Политика перевода текста: отключен (off), авто (auto) или ручной"),
        "translation_style": SettingDescriptor(titleRU: "Стиль перевода", groupRU: "Перевод и языки", descriptionRU: "Тональность перевода (neutral, formal, casual, expressive)"),
        "ui_last_tab": SettingDescriptor(titleRU: "Последняя активная вкладка", groupRU: "Основные и вставка", descriptionRU: "Идентификатор вкладки интерфейса, открытой перед закрытием"),
        "update_channel": SettingDescriptor(titleRU: "Канал обновлений", groupRU: "Безопасность и приватность", descriptionRU: "Ветка получения релизов приложения (stable, beta)"),
        "voice_fingerprint_enabled": SettingDescriptor(titleRU: "Голосовые отпечатки", groupRU: "Диаризация и спикеры", descriptionRU: "Идентификация постоянных спикеров по акустическому профилю"),
        "voice_fingerprint_match_threshold": SettingDescriptor(titleRU: "Порог распознавания голоса", groupRU: "Диаризация и спикеры", descriptionRU: "Чувствительность сравнения голосовых отпечатков (0.0–1.0)"),
        "voice_gateway_api_key": SettingDescriptor(titleRU: "API-ключ Voice Gateway", groupRU: "Звонки и встречи", descriptionRU: "Токен авторизации для связи с Voice Gateway"),
        "voice_gateway_url": SettingDescriptor(titleRU: "URL шлюза Voice Gateway", groupRU: "Звонки и встречи", descriptionRU: "Сетевой адрес локального телефонного шлюза Voice Gateway"),
        "voxtral_enabled": SettingDescriptor(titleRU: "Активировать Voxtral", groupRU: "Языковые модели и LLM", descriptionRU: "Использовать экспериментальную сквозную речевую модель Voxtral"),
        "voxtral_model": SettingDescriptor(titleRU: "Модель Voxtral", groupRU: "Языковые модели и LLM", descriptionRU: "Идентификатор весов модели Voxtral на HuggingFace/диске"),
        "voxtral_reasoning_enabled": SettingDescriptor(titleRU: "Рассуждения в Voxtral", groupRU: "Языковые модели и LLM", descriptionRU: "Включить генерацию рассуждений и цепочки мыслей Voxtral"),
        "wake_word_enabled": SettingDescriptor(titleRU: "Голосовая активация (Wake Word)", groupRU: "Wake Word и ассистент", descriptionRU: "Включение фонового прослушивания ключевой фразы активации"),
        "wake_word_engine": SettingDescriptor(titleRU: "Движок голосовой активации", groupRU: "Wake Word и ассистент", descriptionRU: "Используемая библиотека детекции wake word (openwakeword, porcupine)"),
        "wake_word_stale_sec": SettingDescriptor(titleRU: "Таймаут зависания Wake Word", groupRU: "Wake Word и ассистент", descriptionRU: "Время отсутствия heartbeat до перезапуска детектора (секунды)"),
        "wake_word_watchdog_enabled": SettingDescriptor(titleRU: "Сторожевой таймер Wake Word", groupRU: "Wake Word и ассистент", descriptionRU: "Мониторинг зависания потока распознавания ключевого слова"),
        "whisper_idle_unload_sec": SettingDescriptor(titleRU: "Выгрузка Whisper при простое", groupRU: "Распознавание речи (STT)", descriptionRU: "Таймаут выгрузки моделей Whisper из памяти MLX/GPU"),
    ]
}
